[project]
name = "oct-registration-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dask>=2025.5.1",
    "numpy>=2.3.1",
    "torch>=2.7.1",
]
